/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CartHeader: typeof import('./src/components/CartVeiw/CartHeader.vue')['default']
    Commodity: typeof import('./src/components/HomeView/commodity.vue')['default']
    Favorite: typeof import('./src/components/VideoView/favorite.vue')['default']
    GoodsCard: typeof import('./src/components/CartVeiw/GoodsCard.vue')['default']
    Like: typeof import('./src/components/VideoView/like.vue')['default']
    Message: typeof import('./src/components/VideoView/message.vue')['default']
    MiniCommodity: typeof import('./src/components/VideoView/miniCommodity.vue')['default']
    Purchase: typeof import('./src/components/DetailView/purchase.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettleFee: typeof import('./src/components/CartVeiw/SettleFee.vue')['default']
    SettleHeader: typeof import('./src/components/SettleVeiw/SettleHeader.vue')['default']
    Share: typeof import('./src/components/VideoView/share.vue')['default']
    ShopCard: typeof import('./src/components/CartVeiw/ShopCard.vue')['default']
    Swipe: typeof import('./src/components/HomeView/Swipe.vue')['default']
    Topbar: typeof import('./src/components/HomeView/Topbar.vue')['default']
    ToTop: typeof import('./src/components/DetailView/toTop.vue')['default']
    VanAddressList: typeof import('vant/es')['AddressList']
    VanButton: typeof import('vant/es')['Button']
    VanCard: typeof import('vant/es')['Card']
    VanCell: typeof import('vant/es')['Cell']
    VanCheckbox: typeof import('vant/es')['Checkbox']
    VanCollapse: typeof import('vant/es')['Collapse']
    VanCollapseItem: typeof import('vant/es')['CollapseItem']
    VanCountDown: typeof import('vant/es')['CountDown']
    VanGrid: typeof import('vant/es')['Grid']
    VanGridItem: typeof import('vant/es')['GridItem']
    VanIcon: typeof import('vant/es')['Icon']
    VanLoading: typeof import('vant/es')['Loading']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanSearch: typeof import('vant/es')['Search']
    VanStep: typeof import('vant/es')['Step']
    VanSteps: typeof import('vant/es')['Steps']
    VanSticky: typeof import('vant/es')['Sticky']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    VanTab: typeof import('vant/es')['Tab']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTabs: typeof import('vant/es')['Tabs']
    VanTag: typeof import('vant/es')['Tag']
    VanToast: typeof import('vant/es')['Toast']
  }
}
